baseURL: https://phillycommunitywireless.org
languageCode: en-us
defaultContentLanguage: en
title: Philly Community Wireless
theme: pcw-hugo-theme

languages:
  en:
    contentDir: content/en
    title: Philly Community Wireless
    weight: 1
  sp:
    contentDir: content/sp
    title: Philly Community Wireless
    weight: 2

taxonomies:
  tag: tags

params:
  # description: Building community-owned and operated internet.
  favicon: ""
  # theme
  site_logo: /images/logo.svg
  featured_image: /images/hero.jpg
  cover_dimming_class: bg-black-10
  background_color_class: bg-black-90
  body_classes: helvetica black
  custom_css:
    - custom.css

menu:
  main:
    - name: About Us
      url: /about
      weight: 3
    - name: Get Connected
      url: /getconnected
      weight: 1
    - name: Volunteer
      url: /volunteer
      weight: 2
    - name: FAQ
      url: /faq
      weight: 5
    - name: People
      url: /people
      weight: 4
    - name: Docs
      url: https://docs.phillycommunitywireless.org/en/latest/
      params:
        external: true
      weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true
