baseURL: https://phillycommunitywireless.org
languageCode: en-us
defaultContentLanguage: en
title: Philly Community Wireless
theme: pcw-hugo-theme

languages:
  en:
    languageName: English
    contentDir: content/en
    menu:
      main:
      - name: Home
        url: /
        weight: 0
      - name: About Us
        url: /about
        weight: 3
      - name: Get Connected
        url: /getconnected
        weight: 1
      - name: Volunteer
        url: /volunteer
        weight: 2
      - name: FAQ
        url: /faq
        weight: 5
      - name: People
        url: /people
        weight: 4
      - name: Docs
        url: https://docs.phillycommunitywireless.org/en/latest/
        params:
          external: true
        weight: 10
    weight: 10
  sp:
    languageName: Spanish
    contentDir: content/sp
    menu:
      main:
      - name: Pagina Principal
        url: /sp/
        weight: 0
      - name: Acerca de Nuestros
        url: /sp/about
        weight: 3
      - name: Conéctate
        url: /sp/getconnected
        weight: 1
      - name: Voluntario
        url: /sp/volunteer
        weight: 2
      - name: FAQ
        url: /sp/faq
        weight: 5
      - name: Gente
        url: /sp/people
        weight: 4
      - name: Docs
        url: https://docs.phillycommunitywireless.org/en/latest/
        params:
          external: true
        weight: 20
    weight: 2

taxonomies:
  tag: tags

params:
  # description: Building community-owned and operated internet.
  favicon: ""
  # theme
  site_logo: /images/logo.svg
  featured_image: /images/hero.jpg
  cover_dimming_class: bg-black-10
  background_color_class: bg-black-90
  body_classes: helvetica black
  custom_css:
    - custom.css

markup:
  goldmark:
    renderer:
      unsafe: true
