baseURL: https://phillycommunitywireless.org
languageCode: en-us
defaultContentLanguage: en
title: Philly Community Wireless
theme: pcw-hugo-theme

languages:
  en:
    languageName: English
    contentDir: content/en
    menu:
      main:
        # - name: Home
        #   url: /
        #   weight: 0
        - name: Get Connected
          url: /getconnected
          weight: 1
        - name: Volunteer
          url: /volunteer
          weight: 2
        - name: About Us
          url: /about
          weight: 3
        - name: People
          url: /people
          weight: 4
        - name: FAQ
          url: /faq
          weight: 5
        - name: Docs
          url: https://docs.phillycommunitywireless.org/en/latest/
          params:
            external: true
          weight: 10
      footer:
        - name: Code of Conduct
          url: /code-of-conduct
          weight: 1
        - name: Contact us
          url: /#contact-us
          weight: 2
    weight: 1
  es:
    languageName: Español
    contentDir: content/es
    menu:
      main:
        # - name: Pagina Principal
        #   url: /
        #   weight: 0
        - name: Conéctate
          url: /getconnected
          weight: 1
        - name: Voluntario
          url: /volunteer
          weight: 2
        - name: Acerca
          url: /about
          weight: 3
        - name: Equipo
          url: /people
          weight: 4
        - name: FAQ
          url: /faq
          weight: 5
        - name: Docs
          url: https://docs.phillycommunitywireless.org/es/latest/
          params:
            external: true
          weight: 10
      footer:
        - name: Código de conducta
          url: /code-of-conduct
          weight: 1
        - name: Contáctenos
          url: /#contáctenos
          weight: 2
    weight: 2

params:
  favicon: /images/logo-purple.svg
  # Logo in the navbar
  site_logo: /images/WebLogo_Standard2.svg
  # Hero image
  featured_image: 
    src: /images/hero3.jpg
    alt: A photo of an antenna installed on a rooftop, pointing at a receiver tower in the distance.
  # Text overlay on the hero image 
  featured_text:
    # SVG is allowed in the header
    header: /images/WebLogo_Standard.svg
    subtitle: Building community-controlled networks in Philadelphia
    link: Learn more &rarr;
  # Footer background color
  background_color_class: bg-near-white black-60
  # Add classes to the <body>
  body_classes: calibre black
  # Load these files from assets/pcw-hugo-theme/css
  custom_css:
    - custom.css

markup:
  goldmark:
    renderer:
      # Allow HTML in markdown
      unsafe: true
