baseURL: https://phillycommunitywireless.org
languageCode: en-us
defaultContentLanguage: en
title: Philly Community Wireless
theme: pcw-hugo-theme

languages:
  en:
    languageName: English
    contentDir: content/en
    menu:
      main:
        # - name: Home
        #   url: /
        #   weight: 0
        - name: Get Connected
          url: /getconnected
          weight: 1
        - name: Volunteer
          url: /volunteer
          weight: 2
        - name: About Us
          url: /about
          weight: 3
        - name: People
          url: /people
          weight: 4
        - name: FAQ
          url: /faq
          weight: 5
        - name: Docs
          url: https://docs.phillycommunitywireless.org/en/latest/
          params:
            external: true
          weight: 10
    weight: 1
  es:
    languageName: Español
    contentDir: content/es
    menu:
      main:
        # - name: Pagina Principal
        #   url: /
        #   weight: 0
        - name: Conéctate
          url: /getconnected
          weight: 1
        - name: Voluntario
          url: /volunteer
          weight: 2
        - name: Acerca
          url: /about
          weight: 3
        - name: Equipo
          url: /people
          weight: 4
        - name: FAQ
          url: /faq
          weight: 5
        - name: Docs
          url: https://docs.phillycommunitywireless.org/es/latest/
          params:
            external: true
          weight: 10
    weight: 2

params:
  # theme
  site_logo: /images/logo.svg
  featured_image: /images/hero.jpg
  cover_dimming_class: bg-black-10
  background_color_class: bg-dark-gray
  body_classes: helvetica black
  custom_css:
    - custom.css

markup:
  goldmark:
    renderer:
      # Allow HTML in markdown
      unsafe: true
