baseURL: https://phillycommunitywireless/
languageCode: en-us
defaultContentLanguage: en
title: Philly Community Wireless
theme: ananke

languages:
  en:
    contentDir: content/en
    title: Philly Community Wireless
    weight: 1
  # add spanish TODO

taxonomies:
  tag: tags

params:
  description: Building community-owned and operated internet.
  favicon: ""
  site_logo: images/logo.svg
  # theme
  background_color_class: bg-gold
  featured_image: /images/hero.jpg
  body_classes: avenir black
  custom_css:
    - custom.css

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Get Connected
      url: https://docs.google.com/forms/d/e/1FAIpQLSfjx0A9mFxMiXSb1jisgcHFHwTzktsuz4c36Ja1tVOQjjXzow/viewform
      weight: 2
    - name: Volunteer
      url: /volunteer
      weight: 3
    - name: FAQ
      url: /faq
      weight: 4
    - name: About
      url: /about
      weight: 5
    - name: Blog
      url: /post/
      weight: 6
    - name: Docs
      url: https://docs.phillycommunitywireless.org/en/latest/
      weight: 7
