# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

description = "A Hugo theme for the PCW Project based on Ananke"
features = ["posts", "shortcodes", "related content", "comments"]
homepage = "https://github.com/phillycommunitywireless/phillycommunitywireless"
license = "MIT"
licenselink = "https://github.com/phillycommunitywireless/phillycommunitywireless/blob/master/themes/pcw-hugo-theme/LICENSE.md"
min_version = "0.64.0"
name = "PCW Hugo Theme"
tags = ["mesh"]

[author]
homepage = "https://addieis.online"
name = "Addie Barron"
